module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/tests"],
  testMatch: ["**/*.test.ts"],
  setupFilesAfterEnv: ["<rootDir>/tests/setup.ts"],
   setupFiles: ['<rootDir>/tests/test-env.js'],
  collectCoverageFrom: [
    "app/**/*.ts",
    "!app/app.ts",
    "!src/types/**",
    "!app/types/**",
    "app/**/*.ts",
    "!app/**/*.d.ts",
  ],
  coverageDirectory: "coverage",
  verbose: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  testTimeout: 10000,
  detectOpenHandles: true,
};
